#!/bin/bash

# copy the config files
cp /home/vagrant/dhcp/default /etc/default/isc-dhcp-server
chown root:root /etc/default/isc-dhcp-server
chmod 644 /etc/default/isc-dhcp-server

cp /home/vagrant/dhcp/config /etc/dhcp/dhcpd.conf
chown root:root /etc/dhcp/dhcpd.conf
chmod 644 /etc/dhcp/dhcpd.conf

#install the dhcp server
export DEBIAN_FRONTEND=noninteractive
apt-get -y update
apt-get -y upgrade
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install isc-dhcp-server
